### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by victor-homyakov** [itwillwork/dependencies-tree-builder#3]
Sometimes I see an error when using this package

```
(node:67818) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'slice' of undefined
    at /project/node_modules/dependencies-tree-builder/src/scoupe_factory.js:61:40
    at Array.filter (<anonymous>)
    at /project/node_modules/dependencies-tree-builder/src/scoupe_factory.js:54:44
    at Array.forEach (<anonymous>)
    at /project/node_modules/dependencies-tree-builder/src/scoupe_factory.js:48:19
    at Array.forEach (<anonymous>)
    at ScoupeFactory._dedupeUsages (/project/node_modules/dependencies-tree-builder/src/scoupe_factory.js:44:27)
    at ScoupeFactory.create (/project/node_modules/dependencies-tree-builder/src/scoupe_factory.js:117:10)
    at module.exports (/project/node_modules/dependencies-tree-builder/src/index.js:45:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by victor-homyakov** [comment]
More info.

At the line
```js
const { usages, tunable } = data;
```
(https://github.com/itwillwork/dependencies-tree-builder/blob/master/src/scoupe_factory.js#L49)

object `data` has the following value:

```
{
  usages: [ undefined, undefined, undefined, undefined, undefined ],
  version: undefined,
  name: undefined,
  tunable: true
}
```

**Comment by victor-homyakov** [comment]
Monkey-patching helps to see at least some results

```diff
        const { usages, tunable } = data;

        const carriers = {};

        const sortedUsages = [...usages].sort(byLengthAsc);
-       const dedupedUsages = sortedUsages.filter(usage => {
+       const dedupedUsages = sortedUsages.filter((usage = []) => {
          let startUsagePath = 1;

          if (hasOnlyOneVersion || tunable) {
            startUsagePath = 0;
          }

          const effectiveUsage = usage.slice(startUsagePath);
```

**Comment by victor-homyakov** [comment]
The problem is in package cache. If cache already exists and has _any_ (even outdated) information about some library, then this information is used.

Steps to reproduce:
1. Create package.json with some dependency, say X@1.0.0 (1.0.0 is the latest version)
2. Run dependencies tree builder
3. It creates `node_modules/dependencies-tree-builder/.packages.cache.json` where are listed all currently known versions of dependency X (e.g. 0.9.0, 1.0.0)
4. Release the new version of X (e.g. X@1.1.0), and update dependency in package.json (X@1.0.0 -> X@1.1.0)
5. Run dependencies tree builder again. Now it finds already existing cache, the cache [knows about the library X](https://github.com/itwillwork/dependencies-tree-builder/blob/master/src/package_collector.js#L41), but the cache [does not contain any information about X@1.1.0](https://github.com/itwillwork/dependencies-tree-builder/blob/master/src/package_collector.js#L56)!

**Comment by victor-homyakov** [comment]
Right now the easiest way to avoid this error is to delete `node_modules/dependencies-tree-builder/.packages.cache.json` just before running dependencies tree builder or use corresponding option

```js
const buildTreeAsync = require('dependencies-tree-builder');
const {scoupe} = await buildTreeAsync(packageJson, {useCache: false});
```
